/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const awsExports = {
  aws_project_region: 'us-east-1',
  aws_appsync_graphqlEndpoint:
    'https://vmroe7psrve5jnzdap6yrpmxpi.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-rer2cl7inba27jw3o4ummxv2zy',
  aws_cognito_identity_pool_id:
    'us-east-1:e5ebeee9-a885-4bd9-a220-abb4ef9e0d59',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_N7Uon4qES',
  aws_user_pools_web_client_id: '2nc2llfm0dafa59pvc5r2f71sa',
  oauth: {},
  aws_cognito_username_attributes: ['EMAIL'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: [
    'EMAIL',
    'NAME',
    'NICKNAME',
    'GENDER',
    'PHONE_NUMBER',
    'PICTURE',
    'UPDATED_AT',
    'LOCALE'
  ],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: []
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_user_files_s3_bucket: 'blito-storage-f45ca4aa44547-staging',
  aws_user_files_s3_bucket_region: 'us-east-1'
}
