projects:
  Blito:
    schemaPath: amplify/backend/api/Blito/build/schema.graphql
    includes:
      - packages/blito-models/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: packages/blito-models/API.ts
        docsFilePath: packages/blito-models/graphql
        region: us-east-1
        apiId: 35jolub6zvaktn5xbpx45kw674
        maxDepth: 10
extensions:
  amplify:
    version: 3
