export enum ERROR_CODES {
  /** Error general */
  GEN_BAD_REQUEST = 'GEN001',
  GEN_PAYLOAD_INVALID = 'GEN002',
  GEN_COGNITO_CREDENTIAL_INVALID = 'GEN003',

  /** Errors modules users */
  USE_ERROR_COGNITO = 'USE001',
  USE_USER_NOT_FOUND_IN_DB = 'USE002',
  USE_ERROR_UPDATE = 'USE003',
  USE_EMAIL_ALREADY_EXISTS = 'USE004',
  USE_ERROR_S3 = 'USE005'
}
