/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://gzw7npcnxzbbfidiv6izaqig2u.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-ue5gzet7b5eklmne2krjnb3dxe",
    "aws_cognito_identity_pool_id": "us-east-1:28adc326-42d2-4e2f-98d7-50390a268036",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1RS1isJNy",
    "aws_user_pools_web_client_id": "6lqsabor4lo6hogkllpak4sed0",
    "oauth": {
        "domain": "dev-blito44e1913d-44e1913d-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://dev.blito.co/o-auth/",
        "redirectSignOut": "https://dev.blito.co/o-auth/sign-out/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME",
        "NICKNAME",
        "GENDER",
        "PHONE_NUMBER",
        "PICTURE",
        "UPDATED_AT",
        "LOCALE"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": "8",
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "blito-storage-f45ca4aa133401-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
